name: 'GCP-Stop-Simple-Proxy'
description: 'Stop Running the simple-proxy instance on Google Cloud Platform'
author: 'RamSeraph'

inputs:
  gcp-zone:
    description: 'GCP zone where proxy is running'
    required: true
  gcp-project:
    description: 'GCP project to use'
    required: true
  gcp-credentials:
    description: 'GCP credentials'
    required: false
    default: ''
  gcp-instance-name:
    description: 'GCP instance name'
    required: true

runs:
  using: "composite"
  steps: 
    - name: Authenticate with GCP
      if: inputs.gcp-credentials != ''
      shell: bash
      run: |
        gcloud auth activate-service-account --key-file=<(echo ${{ inputs.gcp-credentials }} | base64 -d)

    - name: Stop
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/stop_js/stop.sh "${{ inputs.gcp-zone }}" "${{ inputs.gcp-project }}" "${{ inputs.gcp-instance-name }}"

